# 1. Import the NUMPY package under the name np.


In [5]:
import numpy as np
import random

# 2. Print the NUMPY version and the configuration.


In [7]:
print("NumPy Version:", np.__version__)
print("NumPy Configuration:")
print(np.show_config())

NumPy Version: 1.24.3
NumPy Configuration:
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/usuario/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/usuario/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/usuario/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/usuario/anaconda3\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/usuario/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/usuario/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/usuario/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', 

# 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"


In [9]:
a = np.random.random((2, 3, 5))
print(a)

[[[0.20371538 0.76248619 0.0703672  0.11182408 0.52722839]
  [0.5193722  0.585888   0.24327654 0.26785671 0.68955697]
  [0.27306234 0.9640056  0.38714681 0.86870384 0.4218912 ]]

 [[0.803184   0.34962851 0.25855186 0.24830883 0.46461755]
  [0.8450328  0.06439574 0.00857689 0.43531211 0.10243173]
  [0.34587154 0.20046233 0.67227009 0.42710673 0.43800783]]]


# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [13]:
a = np.random.random((2, 3, 5))
b = np.random.rand(2, 3, 5)
c = np.random.randn(2, 3, 5)
print(f"esto es a:\n {a}")
print(f"esto es b:\n {b}")
print(f"esto es c:\n {c}")

esto es a:
 [[[0.44119926 0.07364057 0.41491598 0.20759116 0.18868822]
  [0.86147302 0.0140996  0.68001684 0.47812446 0.29567583]
  [0.17940963 0.18732466 0.57288108 0.17277935 0.91434247]]

 [[0.85121329 0.92842521 0.43370408 0.71083908 0.37092579]
  [0.2962207  0.23504265 0.1583785  0.11702371 0.19544287]
  [0.04917019 0.07555929 0.11455642 0.09126778 0.61180491]]]
esto es b:
 [[[0.08655574 0.82320803 0.02594438 0.80165348 0.16573196]
  [0.81365249 0.5615189  0.16880526 0.47931415 0.95978011]
  [0.47728541 0.97945841 0.19798479 0.61763364 0.93926947]]

 [[0.19130026 0.64245491 0.37894128 0.06110863 0.0964341 ]
  [0.37953692 0.12801654 0.94741008 0.62816441 0.54735669]
  [0.08429223 0.22375457 0.57644715 0.46897843 0.520165  ]]]
esto es c:
 [[[-0.16744511  2.03581584 -2.06264644 -1.54917202 -0.00622479]
  [-1.90191843 -0.58586768  1.37391352 -1.40772556 -0.10178195]
  [ 0.76858198  0.11018161  0.04396812 -0.49902641  1.0372408 ]]

 [[ 0.16487582 -1.20901562 -0.13591817 -0.54639775 -1.

# 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
# Assign the array to variable "b"


In [22]:
b = np.ones((5, 2, 3))
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


# 7. Do a and b have the same size? How do you prove that in Python code?


In [29]:
size = b.size == a.size
shape = b.shape == a.shape
print(size)
print(shape)

True
False


# 8. Are you able to add a and b? Why or why not?


In [26]:
suma_arrays = a + b
suma_arrays# no se puede por que a pesar de tener el mismo size no tiene la misma shape

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

# 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [30]:
c = np.transpose(b, (1, 2, 0))
c.shape == a.shape

True

# 10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?


In [32]:
d = c + a
d # por que ahora si que tienen la misma shape

array([[[1.44119926, 1.07364057, 1.41491598, 1.20759116, 1.18868822],
        [1.86147302, 1.0140996 , 1.68001684, 1.47812446, 1.29567583],
        [1.17940963, 1.18732466, 1.57288108, 1.17277935, 1.91434247]],

       [[1.85121329, 1.92842521, 1.43370408, 1.71083908, 1.37092579],
        [1.2962207 , 1.23504265, 1.1583785 , 1.11702371, 1.19544287],
        [1.04917019, 1.07555929, 1.11455642, 1.09126778, 1.61180491]]])

# 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [33]:
print(a)
print(d) # se puede observar que los valores del primer array son todos inferiores a uno mientras que d no, ya que es una suma de los arrays anteriores

[[[0.44119926 0.07364057 0.41491598 0.20759116 0.18868822]
  [0.86147302 0.0140996  0.68001684 0.47812446 0.29567583]
  [0.17940963 0.18732466 0.57288108 0.17277935 0.91434247]]

 [[0.85121329 0.92842521 0.43370408 0.71083908 0.37092579]
  [0.2962207  0.23504265 0.1583785  0.11702371 0.19544287]
  [0.04917019 0.07555929 0.11455642 0.09126778 0.61180491]]]
[[[1.44119926 1.07364057 1.41491598 1.20759116 1.18868822]
  [1.86147302 1.0140996  1.68001684 1.47812446 1.29567583]
  [1.17940963 1.18732466 1.57288108 1.17277935 1.91434247]]

 [[1.85121329 1.92842521 1.43370408 1.71083908 1.37092579]
  [1.2962207  1.23504265 1.1583785  1.11702371 1.19544287]
  [1.04917019 1.07555929 1.11455642 1.09126778 1.61180491]]]


# 12. Multiply a and c. Assign the result to e.


In [34]:
e = a * c
a

array([[[0.44119926, 0.07364057, 0.41491598, 0.20759116, 0.18868822],
        [0.86147302, 0.0140996 , 0.68001684, 0.47812446, 0.29567583],
        [0.17940963, 0.18732466, 0.57288108, 0.17277935, 0.91434247]],

       [[0.85121329, 0.92842521, 0.43370408, 0.71083908, 0.37092579],
        [0.2962207 , 0.23504265, 0.1583785 , 0.11702371, 0.19544287],
        [0.04917019, 0.07555929, 0.11455642, 0.09126778, 0.61180491]]])

# 13. Does e equal to a? Why or why not?


In [36]:
e == a
print(a)
print(e) # son iguales por que los valores son equitativos en ambos arrays

[[[0.44119926 0.07364057 0.41491598 0.20759116 0.18868822]
  [0.86147302 0.0140996  0.68001684 0.47812446 0.29567583]
  [0.17940963 0.18732466 0.57288108 0.17277935 0.91434247]]

 [[0.85121329 0.92842521 0.43370408 0.71083908 0.37092579]
  [0.2962207  0.23504265 0.1583785  0.11702371 0.19544287]
  [0.04917019 0.07555929 0.11455642 0.09126778 0.61180491]]]
[[[0.44119926 0.07364057 0.41491598 0.20759116 0.18868822]
  [0.86147302 0.0140996  0.68001684 0.47812446 0.29567583]
  [0.17940963 0.18732466 0.57288108 0.17277935 0.91434247]]

 [[0.85121329 0.92842521 0.43370408 0.71083908 0.37092579]
  [0.2962207  0.23504265 0.1583785  0.11702371 0.19544287]
  [0.04917019 0.07555929 0.11455642 0.09126778 0.61180491]]]


# 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [40]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()
print(d_max)
print(d_min)
print(d_mean)

1.9284252104009116
1.0140996010312624
1.3640578871453024


# 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [41]:
f = np.empty((2,3,5))
f

array([[[0.44119926, 0.07364057, 0.41491598, 0.20759116, 0.18868822],
        [0.86147302, 0.0140996 , 0.68001684, 0.47812446, 0.29567583],
        [0.17940963, 0.18732466, 0.57288108, 0.17277935, 0.91434247]],

       [[0.85121329, 0.92842521, 0.43370408, 0.71083908, 0.37092579],
        [0.2962207 , 0.23504265, 0.1583785 , 0.11702371, 0.19544287],
        [0.04917019, 0.07555929, 0.11455642, 0.09126778, 0.61180491]]])


"""
# 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""

In [52]:
for i in range(len(d)):
    for j in range(len(d[i])):
        value = d[i][j]  

f[(d > d_min) & (d < d_mean)] = 25
f[(d > d_mean) & (d < d_max)] = 75
f[d == d_mean] = 50
f[d == d_min] = 0
f[d == d_max] = 100
            
print("Array 'f' después de la asignación:")
for row in f:
    print(row)

Array 'f' después de la asignación:
[[75. 25. 75. 25. 25.]
 [75.  0. 75. 75. 25.]
 [25. 25. 75. 25. 75.]]
[[ 75. 100.  75.  75.  75.]
 [ 25.  25.  25.  25.  25.]
 [ 25.  25.  25.  25.  75.]]


# 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""


In [50]:
print(d)
print(f)

[[[1.44119926 1.07364057 1.41491598 1.20759116 1.18868822]
  [1.86147302 1.0140996  1.68001684 1.47812446 1.29567583]
  [1.17940963 1.18732466 1.57288108 1.17277935 1.91434247]]

 [[1.85121329 1.92842521 1.43370408 1.71083908 1.37092579]
  [1.2962207  1.23504265 1.1583785  1.11702371 1.19544287]
  [1.04917019 1.07555929 1.11455642 1.09126778 1.61180491]]]
[[[ 75.  25.  75.  25.  25.]
  [ 75.   0.  75.  75.  25.]
  [ 25.  25.  75.  25.  75.]]

 [[ 75. 100.  75.  75.  75.]
  [ 25.  25.  25.  25.  25.]
  [ 25.  25.  25.  25.  75.]]]


"""
# 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""